project:
  type: website
  output-dir: docs
  
website:
  title: "Bella Ball"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - resume.qmd
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/bellarball
      - icon: github
        href: https://github.com/bellbow/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Bella Ball"

format:
  html:
    theme: quartz
    toc: true

editor: source

